package ESI.TP.Clinic.Modules.test;

public enum categorieQuestionEnfant implements categorieQuestion{
    STRUCTURE_FAMILIALE ,DYNAMIQUE_FAMILIALE , ANTECEDANTS_FAMILIAUX ,CONDITIONS_NATALES ,DEVELOPPEMENT_PSYCHOMOTEUR ,DEVELOPPEMENT_LANGAGIER , CARACTERE_ET_COMPORTEMENTS ;
}
